config {
  type: "table",
  schema: dataform.projectConfig.vars.cdmDataset
}

SELECT
    'dataform-fhir-omop' AS cdm_source_name
    , 'dataform-fhir-omop' AS cdm_source_abbreviation
    , 'N/A' AS cdm_holder
    , 'An OMOP CDM derived from FHIR data (Cloud Healthcare API Analytics V2 export) via a Dataform/BigQuery pipeline.' AS source_description
    , 'https://github.com/sudsk/dataform-fhir-omop' AS source_documentation_reference
    , 'https://github.com/sudsk/dataform-fhir-omop' AS cdm_etl_reference
    , current_date AS source_release_date
    , current_date AS cdm_release_date
    , '5.4' AS cdm_version
    , vocabulary_version
    , 798878 AS cdm_version_concept_id
FROM ${ref("stg_vocabulary__vocabulary")}
WHERE vocabulary_id = 'None'
