config {
  type: "table",
  schema: dataform.projectConfig.vars.cdmDataset
}

WITH all_measurements AS (
    SELECT * FROM ${ref("int__measurement_observations")}
    UNION ALL
    SELECT * FROM ${ref("int__measurement_procedures")}
)

SELECT
    ROW_NUMBER() OVER (ORDER BY person_id) AS measurement_id
    , person_id
    , measurement_concept_id
    , measurement_date
    , measurement_datetime
    , CAST(measurement_time AS STRING) AS measurement_time -- for some reason CDM spec wants this as varchar
    , 32827 AS measurement_type_concept_id
    , CAST(null AS INT64) AS operator_concept_id
    , value_as_number
    , value_as_concept_id
    , unit_concept_id
    , CAST(null AS FLOAT64) AS range_low
    , CAST(null AS FLOAT64) AS range_high
    , provider_id
    , visit_occurrence_id
    , visit_detail_id
    , SUBSTR(measurement_source_value, 1, 50) AS measurement_source_value
    , measurement_source_concept_id
    , SUBSTR(unit_source_value, 1, 50) AS unit_source_value
    , SUBSTR(value_source_value, 1, 50) AS value_source_value
    , CAST(null AS INT64) AS unit_source_concept_id
    , CAST(null AS INT64) AS measurement_event_id
    , CAST(null AS INT64) AS meas_event_field_concept_id
FROM all_measurements
