config {
  type: "table",
  schema: dataform.projectConfig.vars.cdmDataset
}

SELECT
    CAST(null AS INT64) AS metadata_id
    , CAST(null AS INT64) AS metadata_concept_id
    , CAST(null AS INT64) AS metadata_type_concept_id
    , CAST(null AS STRING) AS `name`
    , CAST(null AS STRING) AS value_as_string
    , CAST(null AS INT64) AS value_as_concept_id
    , CAST(null AS FLOAT64) AS value_as_number
    , CAST(null AS DATE) AS metadata_date
    , CAST(null AS TIMESTAMP) AS metadata_datetime
WHERE 1 = 0
