config {
  type: "table",
  schema: dataform.projectConfig.vars.cdmDataset
}

SELECT
    CAST(null AS INT64) AS note_id
    , CAST(null AS INT64) AS person_id
    , CAST(null AS DATE) AS note_date
    , CAST(null AS TIMESTAMP) AS note_datetime
    , CAST(null AS INT64) AS note_type_concept_id
    , CAST(null AS INT64) AS note_class_concept_id
    , CAST(null AS STRING) AS note_title
    , CAST(null AS STRING) AS note_text
    , CAST(null AS INT64) AS encoding_concept_id
    , CAST(null AS INT64) AS language_concept_id
    , CAST(null AS INT64) AS provider_id
    , CAST(null AS INT64) AS visit_occurrence_id
    , CAST(null AS INT64) AS visit_detail_id
    , CAST(null AS STRING) AS note_source_value
    , CAST(null AS INT64) AS note_event_id
    , CAST(null AS INT64) AS note_event_field_concept_id
WHERE 1 = 0
