config {
  type: "table",
  schema: dataform.projectConfig.vars.cdmDataset
}

WITH all_observations AS (
    SELECT * FROM ${ref("int__observation_allergies")}
    UNION ALL
    SELECT * FROM ${ref("int__observation_conditions")}
    UNION ALL
    SELECT * FROM ${ref("int__observation_observations")}
)

SELECT
    row_number() OVER (ORDER BY person_id) AS observation_id
    , person_id
    , observation_concept_id
    , observation_date
    , observation_datetime
    , 32817 AS observation_type_concept_id
    , CAST(null AS FLOAT64) AS value_as_number
    , CAST(null AS STRING) AS value_as_string
    , CAST(null AS INT64) AS value_as_concept_id
    , CAST(null AS INT64) AS qualifier_concept_id
    , CAST(null AS INT64) AS unit_concept_id
    , provider_id
    , visit_occurrence_id
    , visit_detail_id
    , SUBSTR(observation_source_value, 1, 50) AS observation_source_value
    , observation_source_concept_id
    , CAST(null AS STRING) AS unit_source_value
    , CAST(null AS STRING) AS qualifier_source_value
    , CAST(null AS STRING) AS value_source_value
    , CAST(null AS INT64) AS observation_event_id
    , CAST(null AS INT64) AS obs_event_field_concept_id
FROM all_observations
