config {
  type: "table",
  schema: dataform.projectConfig.vars.cdmDataset
}

SELECT
    person_id
    , gender_concept_id
    , year_of_birth
    , month_of_birth
    , day_of_birth
    , birth_datetime
    , race_concept_id
    , ethnicity_concept_id
    , location_id
    , CAST(NULL AS INT64)  AS provider_id
    , CAST(NULL AS INT64)  AS care_site_id
    , person_source_value
    , SUBSTR(gender_source_value, 1, 50) AS gender_source_value
    , 0 AS gender_source_concept_id
    , SUBSTR(race_source_value, 1, 50) AS race_source_value
    , 0 AS race_source_concept_id
    , SUBSTR(ethnicity_source_value, 1, 50) AS ethnicity_source_value
    , 0 AS ethnicity_source_concept_id
FROM ${ref("int__person")}
