config {
  type: "table",
  schema: dataform.projectConfig.vars.cdmDataset
}

SELECT
    visit_detail_id
    , person_id
    , visit_detail_concept_id
    , visit_detail_start_date
    , visit_detail_start_datetime
    , visit_detail_end_date
    , visit_detail_end_datetime
    , 32827 AS visit_detail_type_concept_id
    , provider_id
    , CAST(NULL AS INT64)  AS care_site_id
    , CAST(NULL AS INT64) AS admitted_from_concept_id
    , CAST(NULL AS INT64) AS discharged_to_concept_id
    , CAST(NULL AS INT64) AS preceding_visit_detail_id
    , SUBSTR(visit_detail_source_value, 1, 50) AS visit_detail_source_value
    , 0 AS visit_detail_source_concept_id
    , CAST(NULL AS STRING) AS admitted_from_source_value
    , CAST(NULL AS STRING) AS discharged_to_source_value
    , CAST(NULL AS INT64)  AS parent_visit_detail_id
    , visit_occurrence_id
FROM ${ref("int__visit_detail")}
